package governance

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Bundle exports the versioned, checksum-pinned source distribution and launcher.
func Bundle(root string, destinations []string) error {
	if len(destinations) == 0 {
		return fmt.Errorf("bundle requires explicit destination checkout paths")
	}
	var files []string
	candidates, err := SourceFiles(root)
	if err != nil {
		return err
	}
	for _, r := range candidates {
		if strings.HasPrefix(r, "build/") || strings.HasPrefix(r, "coverage/") || strings.HasPrefix(r, "bin/") {
			continue
		}
		if !strings.HasSuffix(r, ".go") && r != "go.mod" && r != "go.sum" {
			continue
		}
		p, err := safePath(root, r)
		if err != nil {
			return err
		}
		info, err := os.Lstat(p)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("source bundle cannot contain symlinks or nonregular files")
		}
		files = append(files, r)
	}
	sort.Strings(files)
	tmp, e := os.CreateTemp("", "ledger-bundle-*.tar.gz")
	if e != nil {
		return e
	}
	name := tmp.Name()
	defer os.Remove(name)
	gz := gzip.NewWriter(tmp)
	tw := tar.NewWriter(gz)
	for _, r := range files {
		b, e := os.ReadFile(filepath.Join(root, r))
		if e != nil {
			_ = tmp.Close()
			return e
		}
		if e = tw.WriteHeader(&tar.Header{Name: filepath.ToSlash(r), Size: int64(len(b)), Mode: 0644, ModTime: time.Unix(0, 0)}); e != nil {
			_ = tmp.Close()
			return e
		}
		if _, e = tw.Write(b); e != nil {
			_ = tmp.Close()
			return e
		}
	}
	if e = tw.Close(); e != nil {
		_ = tmp.Close()
		return e
	}
	if e = gz.Close(); e != nil {
		_ = tmp.Close()
		return e
	}
	if e = tmp.Close(); e != nil {
		return e
	}
	data, e := os.ReadFile(name)
	if e != nil {
		return e
	}
	sum := sha256.Sum256(data)
	launcher, e := os.ReadFile(filepath.Join(root, "bootstrap/bootstrap.go"))
	if e != nil {
		return e
	}
	launcher = append([]byte("// Code generated by ledger-tool bundle; DO NOT EDIT.\n"), launcher...)
	for _, dest := range destinations {
		dest, e = filepath.Abs(dest)
		if e != nil {
			return e
		}
		if _, e = os.Stat(filepath.Join(dest, "governance.json")); e != nil {
			return fmt.Errorf("destination must be a configured checkout: %w", e)
		}
		dir, e := safePath(dest, "tool")
		if e != nil {
			return e
		}
		if e = os.MkdirAll(dir, 0755); e != nil {
			return e
		}
		outputs := map[string]string{}
		for _, name := range []string{"ledger-tooling-v0.1.0.tar.gz", "bootstrap.go", "tooling.lock.json"} {
			p, err := safePath(dest, "tool/"+name)
			if err != nil {
				return err
			}
			outputs[name] = p
		}
		if e = os.WriteFile(outputs["ledger-tooling-v0.1.0.tar.gz"], data, 0644); e != nil {
			return e
		}
		if e = os.WriteFile(outputs["bootstrap.go"], launcher, 0644); e != nil {
			return e
		}
		if e = WriteJSON(outputs["tooling.lock.json"], map[string]string{"version": "0.1.0", "source": "tool/ledger-tooling-v0.1.0.tar.gz", "sha256": hex.EncodeToString(sum[:])}); e != nil {
			return e
		}
	}
	return nil
}
